### ISSUE TITLE
Default Parameters in Point and Endpoint cause issue

### ISSUE THREAD

**Issue by chad-autry** [Silverwolf90/2d-visibility#3]
The visibility lines do not draw (tried Chrome, IE, Firefox)

When debugging, x and y are objects, not integers.
Inspecting the bundle output, the source of Point seems to have been correctly trans-piled to set defaults. 

I attempted to pin the version of all devDependencies to what is listed, but it did not make a difference.
Simply deleting the defaults makes the demo work correctly for me, I don't believe the defaults are actually depended on anywhere.

**Comment by Silverwolf90** [comment]
Thanks, just merged your PR
