### ISSUE TITLE
Move to Typescript

### ISSUE THREAD

**Issue by itbrandonsilva** [Silverwolf90/2d-visibility#5]
Want to start by saying I greatly appreciate you putting this repo together. Definitely helped me get through the content on redblobgames very quickly.

I do feel that moving from Babel to Typescript would help others be able to parse the code much more effectively. I'm looking to learn if you'd be open to the possibility, and I can make a PR transitioning the repo from Babel to Typescript without any code changes whatsoever, and simply adding clear type definitions.

Thanks!

**Comment by Silverwolf90** [comment]
Thanks, I'm really glad to hear you found it useful!

Generally I don't like the added verbosity of static typing, but in this case I think I agree that the code could benefit from it. But I would rather stick with the tooling that I'm familiar with. How do you feel about [Flow](https://flowtype.org/)?

Alternatively, you could fork the repo and I'd happily link to it in the readme.

**Comment by itbrandonsilva** [comment]
Having the readme simply point to a typed version of the repo sounds like a great idea.

Though, I've actually yet to try flow. I'll find some time to try it out and return when I have more perspective.

I'll close the issue, and reopen when I return. Thanks!

**Comment by Petah** [comment]
Hi,

I have made a port of this lib to TypeScript

https://github.com/Petah/2d-visibility

**Comment by Silverwolf90** [comment]
Nice one @Petah! I've linked to it in the readme.
